// flow-typed signature: acaa9dd97fe5890b00c9a37c4b07f227
// flow-typed version: <<STUB>>/nexe_v^2.0.0-rc.34/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nexe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nexe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nexe/lib/bundling/bindings-rewrite' {
  declare module.exports: any;
}

declare module 'nexe/lib/bundling/embed-node' {
  declare module.exports: any;
}

declare module 'nexe/lib/bundling/fuse-native-module-plugin' {
  declare module.exports: any;
}

declare module 'nexe/lib/bundling/index' {
  declare module.exports: any;
}

declare module 'nexe/lib/bundling/pre-gyp-find-rewrite' {
  declare module.exports: any;
}

declare module 'nexe/lib/compiler' {
  declare module.exports: any;
}

declare module 'nexe/lib/logger' {
  declare module.exports: any;
}

declare module 'nexe/lib/nexe' {
  declare module.exports: any;
}

declare module 'nexe/lib/options' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/boot-nexe' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/build-fixes' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/disable-node-cli' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/flags' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/gyp' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/ico' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/index' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/node-rc' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/snapshot' {
  declare module.exports: any;
}

declare module 'nexe/lib/patches/third-party-main' {
  declare module.exports: any;
}

declare module 'nexe/lib/releases' {
  declare module.exports: any;
}

declare module 'nexe/lib/steps/artifacts' {
  declare module.exports: any;
}

declare module 'nexe/lib/steps/bundle' {
  declare module.exports: any;
}

declare module 'nexe/lib/steps/cli' {
  declare module.exports: any;
}

declare module 'nexe/lib/steps/download' {
  declare module.exports: any;
}

declare module 'nexe/lib/steps/resource' {
  declare module.exports: any;
}

declare module 'nexe/lib/steps/shim-fs' {
  declare module.exports: any;
}

declare module 'nexe/lib/steps/shim' {
  declare module.exports: any;
}

declare module 'nexe/lib/target' {
  declare module.exports: any;
}

declare module 'nexe/lib/util' {
  declare module.exports: any;
}

declare module 'nexe/source-map-support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nexe/index' {
  declare module.exports: $Exports<'nexe'>;
}
declare module 'nexe/index.js' {
  declare module.exports: $Exports<'nexe'>;
}
declare module 'nexe/lib/bundling/bindings-rewrite.js' {
  declare module.exports: $Exports<'nexe/lib/bundling/bindings-rewrite'>;
}
declare module 'nexe/lib/bundling/embed-node.js' {
  declare module.exports: $Exports<'nexe/lib/bundling/embed-node'>;
}
declare module 'nexe/lib/bundling/fuse-native-module-plugin.js' {
  declare module.exports: $Exports<'nexe/lib/bundling/fuse-native-module-plugin'>;
}
declare module 'nexe/lib/bundling/index.js' {
  declare module.exports: $Exports<'nexe/lib/bundling/index'>;
}
declare module 'nexe/lib/bundling/pre-gyp-find-rewrite.js' {
  declare module.exports: $Exports<'nexe/lib/bundling/pre-gyp-find-rewrite'>;
}
declare module 'nexe/lib/compiler.js' {
  declare module.exports: $Exports<'nexe/lib/compiler'>;
}
declare module 'nexe/lib/logger.js' {
  declare module.exports: $Exports<'nexe/lib/logger'>;
}
declare module 'nexe/lib/nexe.js' {
  declare module.exports: $Exports<'nexe/lib/nexe'>;
}
declare module 'nexe/lib/options.js' {
  declare module.exports: $Exports<'nexe/lib/options'>;
}
declare module 'nexe/lib/patches/boot-nexe.js' {
  declare module.exports: $Exports<'nexe/lib/patches/boot-nexe'>;
}
declare module 'nexe/lib/patches/build-fixes.js' {
  declare module.exports: $Exports<'nexe/lib/patches/build-fixes'>;
}
declare module 'nexe/lib/patches/disable-node-cli.js' {
  declare module.exports: $Exports<'nexe/lib/patches/disable-node-cli'>;
}
declare module 'nexe/lib/patches/flags.js' {
  declare module.exports: $Exports<'nexe/lib/patches/flags'>;
}
declare module 'nexe/lib/patches/gyp.js' {
  declare module.exports: $Exports<'nexe/lib/patches/gyp'>;
}
declare module 'nexe/lib/patches/ico.js' {
  declare module.exports: $Exports<'nexe/lib/patches/ico'>;
}
declare module 'nexe/lib/patches/index.js' {
  declare module.exports: $Exports<'nexe/lib/patches/index'>;
}
declare module 'nexe/lib/patches/node-rc.js' {
  declare module.exports: $Exports<'nexe/lib/patches/node-rc'>;
}
declare module 'nexe/lib/patches/snapshot.js' {
  declare module.exports: $Exports<'nexe/lib/patches/snapshot'>;
}
declare module 'nexe/lib/patches/third-party-main.js' {
  declare module.exports: $Exports<'nexe/lib/patches/third-party-main'>;
}
declare module 'nexe/lib/releases.js' {
  declare module.exports: $Exports<'nexe/lib/releases'>;
}
declare module 'nexe/lib/steps/artifacts.js' {
  declare module.exports: $Exports<'nexe/lib/steps/artifacts'>;
}
declare module 'nexe/lib/steps/bundle.js' {
  declare module.exports: $Exports<'nexe/lib/steps/bundle'>;
}
declare module 'nexe/lib/steps/cli.js' {
  declare module.exports: $Exports<'nexe/lib/steps/cli'>;
}
declare module 'nexe/lib/steps/download.js' {
  declare module.exports: $Exports<'nexe/lib/steps/download'>;
}
declare module 'nexe/lib/steps/resource.js' {
  declare module.exports: $Exports<'nexe/lib/steps/resource'>;
}
declare module 'nexe/lib/steps/shim-fs.js' {
  declare module.exports: $Exports<'nexe/lib/steps/shim-fs'>;
}
declare module 'nexe/lib/steps/shim.js' {
  declare module.exports: $Exports<'nexe/lib/steps/shim'>;
}
declare module 'nexe/lib/target.js' {
  declare module.exports: $Exports<'nexe/lib/target'>;
}
declare module 'nexe/lib/util.js' {
  declare module.exports: $Exports<'nexe/lib/util'>;
}
declare module 'nexe/source-map-support.js' {
  declare module.exports: $Exports<'nexe/source-map-support'>;
}
