// flow-typed signature: d33e25bd7235420927fff4250aad2544
// flow-typed version: <<STUB>>/@line/bot-sdk_v^6.4.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@line/bot-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@line/bot-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@line/bot-sdk/dist/client' {
  declare module.exports: any;
}

declare module '@line/bot-sdk/dist/exceptions' {
  declare module.exports: any;
}

declare module '@line/bot-sdk/dist/http' {
  declare module.exports: any;
}

declare module '@line/bot-sdk/dist/index' {
  declare module.exports: any;
}

declare module '@line/bot-sdk/dist/middleware' {
  declare module.exports: any;
}

declare module '@line/bot-sdk/dist/types' {
  declare module.exports: any;
}

declare module '@line/bot-sdk/dist/validate-signature' {
  declare module.exports: any;
}

// Filename aliases
declare module '@line/bot-sdk/dist/client.js' {
  declare module.exports: $Exports<'@line/bot-sdk/dist/client'>;
}
declare module '@line/bot-sdk/dist/exceptions.js' {
  declare module.exports: $Exports<'@line/bot-sdk/dist/exceptions'>;
}
declare module '@line/bot-sdk/dist/http.js' {
  declare module.exports: $Exports<'@line/bot-sdk/dist/http'>;
}
declare module '@line/bot-sdk/dist/index.js' {
  declare module.exports: $Exports<'@line/bot-sdk/dist/index'>;
}
declare module '@line/bot-sdk/dist/middleware.js' {
  declare module.exports: $Exports<'@line/bot-sdk/dist/middleware'>;
}
declare module '@line/bot-sdk/dist/types.js' {
  declare module.exports: $Exports<'@line/bot-sdk/dist/types'>;
}
declare module '@line/bot-sdk/dist/validate-signature.js' {
  declare module.exports: $Exports<'@line/bot-sdk/dist/validate-signature'>;
}
